In [2]:
from numpy import *

In [3]:
a = array([2, 3, 4])  # Создание одномерного массива из списка целых чисел

In [6]:
print(a)
a

[2 3 4]


array([2, 3, 4])

In [7]:
a.ndim # Размерность массива (одномерный, двумерный и т.д.)

1

In [8]:
a.shape # Размеры массива (число строк, столбцов и т.д.)

(3,)

In [11]:
b = array([(1.5, 2, 3), (4, 5, 7)])  # Создание двумерного массива из двух последовательностей чисел.

In [12]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  7. ]]


In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
b.size

6

In [16]:
z = zeros((3, 2))  # 3, 2 помещаются в дополнительные скобки, чтобы представлять из себя один объект.

In [17]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
arange(10, 23, 5)  # Функция arange аналогична функции range, но возвращает массив.

array([10, 15, 20])

In [19]:
linspace(0, 2, 12)  # Генерирует 12 чисел на отрезке от 0 до 2 с равным шагом.

array([0.        , 0.18181818, 0.36363636, 0.54545455, 0.72727273,
       0.90909091, 1.09090909, 1.27272727, 1.45454545, 1.63636364,
       1.81818182, 2.        ])

In [20]:
b = arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
a = array([10, 20, 30])
b = arange(3)
print(a)
print(b)

[10 20 30]
[0 1 2]


In [26]:
print(a + b)  # Арифметические операции на массивах выполняются поэлементно.
print(a - b)

[10 21 32]
[10 19 28]


In [27]:
print(a ** 2)  # Возведем массив в квадрат.

[100 400 900]


In [28]:
2 * sin(a)

array([-1.08804222,  1.8258905 , -1.97606325])

In [29]:
a < 20

array([ True, False, False])